name: Build

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DB_USER: ${{ secrets.DBUSER }}
      DB_PASSWORD: ${{ secrets.DBPASSWORD }}
      DB_COLLECTION: ${{ secrets.DBCOLLECTION }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 20.11.1

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Tests
      run: npm run test
